image: python:latest

services:
  - name: postgres:latest

variables:
  POSTGRES_DB: dbadmin
  POSTGRES_USER: dbadmin
  POSTGRES_PASSWORD: "dbadmin"

test:
  script:
  - apt-get update
  - echo 'deb http://apt.postgresql.org/pub/repos/apt/ jessie-pgdg main' > /etc/apt/sources.list.d/pgdg.list
  - wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
  - apt-get update && apt-get upgrade -y && apt-get -y install postgresql-client
  - apt-get install python3 python3-venv python3-dev libpq-dev build-essential -yqq
  - python3 -m venv venv
  - source venv/bin/activate
  - pwd
  - pip3 install --upgrade pip setuptools
  - pip3 install -r requirements.txt
  - python -m unittest discover --verbose
  - python mytest.py
