"""empty message

Revision ID: b38b893343b7
Revises: 
Create Date: 2019-02-15 15:15:34.303820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b38b893343b7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('rules', sa.String(), nullable=True),
    sa.Column('max_threads', sa.Integer(), nullable=True),
    sa.Column('mimetypes', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ext', sa.String(length=4), nullable=False),
    sa.Column('mimetype', sa.String(length=255), nullable=False),
    sa.Column('is_animated', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('slip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('pass_hash', sa.String(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_mod', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('bg_style', sa.String(), nullable=True),
    sa.Column('text_style', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('slip_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['slip_id'], ['slip.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('thread',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('board', sa.Integer(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['board'], ['board.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('poster',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hex_string', sa.String(length=4), nullable=False),
    sa.Column('ip_address', sa.String(length=15), nullable=False),
    sa.Column('thread', sa.Integer(), nullable=False),
    sa.Column('slip', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['slip'], ['slip.id'], ),
    sa.ForeignKeyConstraint(['thread'], ['thread.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['thread.id'], ),
    sa.PrimaryKeyConstraint('tag_id', 'thread_id')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=4096), nullable=False),
    sa.Column('subject', sa.String(length=64), nullable=True),
    sa.Column('thread', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('poster', sa.Integer(), nullable=False),
    sa.Column('media', sa.Integer(), nullable=True),
    sa.Column('spoiler', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['media'], ['media.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['poster'], ['poster.id'], ),
    sa.ForeignKeyConstraint(['thread'], ['thread.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reply',
    sa.Column('reply_from', sa.Integer(), nullable=False),
    sa.Column('reply_to', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['reply_from'], ['post.id'], ),
    sa.ForeignKeyConstraint(['reply_to'], ['post.id'], ),
    sa.PrimaryKeyConstraint('reply_from', 'reply_to')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reply')
    op.drop_table('post')
    op.drop_table('tags')
    op.drop_table('poster')
    op.drop_table('thread')
    op.drop_table('session')
    op.drop_table('tag')
    op.drop_table('slip')
    op.drop_table('media')
    op.drop_table('board')
    # ### end Alembic commands ###
